### ISSUE TITLE
Tooltip for path not working in latest Nightly

### ISSUE THREAD

**Issue by charlesmilette** [Infocatcher/Download_Panel_Tweaker#41] opened 2016-03-12 15:46 UTC
Seems Nightly broke a thing again.
![2016-03-12_10-44-48](https://cloud.githubusercontent.com/assets/6440374/13723854/acdbb742-e83f-11e5-8ae9-70793d854798.png)

**Comment by Infocatcher** [comment] 2016-03-12 16:28
Thanks for report. Was already corrected some days ago: fe6125d9eabba12f8131798867916c5682b6da6d

**Comment by FatOrangutan** [comment] 2016-06-10 06:40
Tooltip for full path and right click -> Remove file from disk don't seem to work in Firefox stable v47.0. I'm on Download Panel Tweaker v0.2.4.1.

**Comment by Infocatcher** [comment] 2016-06-10 17:59
> Tooltip for full path and right click -> Remove file from disk don't seem to work in Firefox stable v47.0. I'm on Download Panel Tweaker v0.2.4.1.

This caused by the same reason...
Should be fixed now:
https://addons.mozilla.org/firefox/addon/download-panel-tweaker/versions/0.2.5

**Closed by Infocatcher** 2016-06-10 17:59 UTC
Labels: bug, compatibility, fixed?
